[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.2.0",
    "flask-login>=0.6.3",
    "flask>=3.1.0",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=23.0.0",
    "psycopg2-binary>=2.9.10",
    "flask-wtf>=1.2.2",
    "tenacity>=9.1.2",
    "werkzeug>=3.1.3",
    "pydub>=0.25.1",
    "stripe>=12.0.0",
    "boto3>=1.37.31",
    "botocore>=1.37.31",
    "sqlalchemy>=2.0.40",
    "openai>=1.72.0",
    "sendgrid>=6.11.0",
    "trafilatura>=2.0.0",
    "pyjwt>=2.10.1",
    "requests>=2.32.3",
    "flask-recaptcha>=0.4.2",
    "anthropic>=0.50.0",
    "twilio>=9.6.0",
    "google-cloud-storage>=3.1.0",
    "wtforms>=3.2.1",
    "google-cloud-core>=2.4.3",
    "redis>=6.0.0",
    "sift-stack-py>=0.5.2",
    "markdown>=3.8",
    "flask-session>=0.8.0",
    "google-auth>=2.40.1",
    "flask-talisman>=1.1.0",
    "celery>=5.5.2",
    "flask-testing>=0.8.1",
    "pytest>=8.3.5",
    "structlog>=25.3.0",
    "geoip2>=5.1.0",
    "qrcode[pil]>=8.2",
    "pillow>=11.2.1",
    "bcrypt>=4.3.0",
    "oauthlib>=3.3.1",
    "flask-dance>=7.1.0",
]
